import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:wholeflow_app/core/api/api_client.dart';
import 'package:wholeflow_app/core/errors/app_failure.dart';
import 'package:wholeflow_app/core/errors/error_reporter.dart';
import 'package:wholeflow_app/core/upgrade/upgrade_gate.dart';
import 'package:wholeflow_app/features/auth/data/auth_repository.dart';
import 'package:wholeflow_app/features/visits/domain/visit.dart';

/// Server contracts the Go integration test doesn't record: the app version
/// headers and HTTP 426 for too-old apps, `reauthentication_needed` for
/// password changes, and client error reports. The answers are hand-written
/// in test/fixtures/handwritten/ (test/fixtures/api/ is regenerated by the
/// Go test, so only its shape is relied on here, never its tokens).
void main() {
  const headers = {'X-App-Version': '1.2.3+45', 'X-App-Platform': 'android'};
  String handwritten(String name) => File('test/fixtures/handwritten/$name.json').readAsStringSync();
  List<int> recorded(String name) => File('test/fixtures/api/$name.json').readAsBytesSync();

  // Lets the gate's deferred update run.
  Future<void> settle() => Future<void>.delayed(Duration.zero);

  setUp(UpgradeGate.reset);

  group('app API: version headers and 426', () {
    late http.Request last;
    ApiClient api(int status, String body) => ApiClient(
      baseUrl: 'https://api.example.test/b/demo',
      token: () async => 'tok',
      headers: headers,
      client: MockClient((req) async {
        last = req;
        return http.Response(body, status, headers: {'content-type': 'application/json'});
      }),
    );

    test('every request carries X-App-Version and X-App-Platform', () async {
      await api(200, '{"ok":true}').get('me');
      expect(last.headers['X-App-Version'], '1.2.3+45');
      expect(last.headers['X-App-Platform'], 'android');
      expect(last.headers['Authorization'], 'Bearer tok');
    });

    test('426 UPGRADE_REQUIRED is upgradeRequired and opens the update screen', () async {
      Object? thrown;
      try {
        await api(426, handwritten('api_upgrade_required')).get('me');
      } catch (e) {
        thrown = e;
      }
      expect(thrown, isA<ApiException>().having((e) => e.code, 'code', 'UPGRADE_REQUIRED'));
      final f = AppFailure.from(thrown!);
      expect(f.kind, FailureKind.upgradeRequired);
      expect(f.message, contains('too old'));
      await settle();
      expect(UpgradeGate.required, isTrue);
      expect(UpgradeGate.message.value, contains('too old'));
    });

    test('other errors leave the app running', () async {
      try {
        await api(404, '{"error":{"code":"NOT_FOUND","message":"x"}}').get('me');
      } catch (_) {}
      await settle();
      expect(UpgradeGate.required, isFalse);
    });
  });

  group('login service: version headers, 426 and reauthentication', () {
    late List<http.Request> sent;
    late bool wrongPassword;
    late (String, int)? userAnswer;

    http.Response answer(List<int> body, int status, {bool apiVersion = true}) => http.Response.bytes(
      body,
      status,
      headers: {'content-type': 'application/json', if (apiVersion) 'x-supabase-api-version': '2024-01-01'},
    );

    SupabaseClient supabase({http.Response Function(http.Request)? override}) {
      sent = [];
      final inner = MockClient((req) async {
        sent.add(req);
        if (override != null) return override(req);
        final path = req.url.path.split('/auth/v1/').last;
        return switch ((req.method, path)) {
          ('POST', 'token') when wrongPassword => answer(recorded('auth_error'), 400),
          ('POST', 'token') => answer(recorded('auth_token'), 200),
          ('PUT', 'user') when userAnswer != null => answer(utf8.encode(userAnswer!.$1), userAnswer!.$2),
          ('PUT', 'user') => answer(recorded('auth_user'), 200),
          _ => http.Response('', 404),
        };
      });
      return SupabaseClient(
        'https://api.example.test/b/apitest',
        'anon',
        headers: headers,
        httpClient: AppHttpClient(headers, inner),
        authOptions: const AuthClientOptions(autoRefreshToken: false),
      );
    }

    setUp(() {
      wrongPassword = false;
      userAnswer = null;
    });

    test('login requests carry the version headers', () async {
      final client = supabase();
      await client.auth.signInWithPassword(email: 'o@a.test', password: 'owner-pass-1');
      expect(sent.single.headers['X-App-Version'], '1.2.3+45');
      expect(sent.single.headers['X-App-Platform'], 'android');
    });

    for (final apiVersion in [true, false]) {
      test('426 upgrade_required is upgradeRequired (api version header: $apiVersion)', () async {
        final client = supabase(
          override: (_) => answer(utf8.encode(handwritten('auth_upgrade_required')), 426, apiVersion: apiVersion),
        );
        Object? thrown;
        try {
          await client.auth.signInWithPassword(email: 'o@a.test', password: 'owner-pass-1');
        } catch (e) {
          thrown = e;
        }
        expect(thrown, isA<AuthException>());
        expect(AppFailure.from(thrown!).kind, FailureKind.upgradeRequired);
        await settle();
        expect(UpgradeGate.required, isTrue);
      });
    }

    test('any 426 from the login service (e.g. a token refresh) opens the update screen', () async {
      final client = supabase(override: (_) => http.Response('', 426));
      try {
        await client.auth.signInWithPassword(email: 'o@a.test', password: 'x');
      } catch (_) {}
      await settle();
      expect(UpgradeGate.required, isTrue);
    });

    AuthRepository repo(SupabaseClient client) =>
        AuthRepository(client, ApiClient(baseUrl: 'https://api.example.test/b/apitest', token: () async => null));

    test('Settings: signs in with the current password, then sets the new one (no metadata sent)', () async {
      final client = supabase();
      await client.auth.signInWithPassword(email: 'o@a.test', password: 'owner-pass-1');
      sent.clear();
      await repo(client).changePassword('owner-pass-2', currentPassword: 'owner-pass-1');
      expect(sent.map((r) => (r.method, r.url.path.split('/').last)), [('POST', 'token'), ('PUT', 'user')]);
      final signIn = jsonDecode(sent.first.body) as Map;
      expect(signIn['password'], 'owner-pass-1');
      expect(signIn['email'], client.auth.currentUser!.email);
      final update = jsonDecode(sent.last.body) as Map;
      expect(update['password'], 'owner-pass-2');
      expect(update.containsKey('data'), isFalse);
      // The server's answer clears the flag; the app reads it from there.
      expect(repo(client).mustChangePassword, isFalse);
    });

    test('Settings: a wrong current password says so and changes nothing', () async {
      final client = supabase();
      await client.auth.signInWithPassword(email: 'o@a.test', password: 'owner-pass-1');
      wrongPassword = true;
      sent.clear();
      Object? thrown;
      try {
        await repo(client).changePassword('owner-pass-2', currentPassword: 'nope');
      } catch (e) {
        thrown = e;
      }
      expect(thrown, isA<AppFailure>().having((f) => f.message, 'message', 'Current password is wrong.'));
      expect(sent.where((r) => r.method == 'PUT'), isEmpty);
      expect(client.auth.currentSession, isNotNull, reason: 'a wrong password keeps the session');
    });

    test('first sign-in screen: no current password; reauthentication_needed is mapped', () async {
      final client = supabase();
      await client.auth.signInWithPassword(email: 'o@a.test', password: 'owner-pass-1');
      userAnswer = (handwritten('auth_reauthentication_needed'), 401);
      sent.clear();
      Object? thrown;
      try {
        await repo(client).changePassword('owner-pass-2');
      } catch (e) {
        thrown = e;
      }
      expect(sent.single.method, 'PUT');
      expect(thrown, isA<AppFailure>().having((f) => f.kind, 'kind', FailureKind.reauthenticationNeeded));
    });
  });

  group('error reports', () {
    late List<Map<String, String>> posted;
    late bool signedIn;
    ErrorReporter reporter() => ErrorReporter(
      post: (body) async => posted.add(body),
      signedIn: () => signedIn,
      appVersion: '1.2.3+45',
      platform: 'android',
      flavor: 'staff',
    );

    setUp(() {
      posted = [];
      signedIn = true;
    });

    test('sends message, stack, version, platform and flavor', () async {
      reporter().report(StateError('boom'), StackTrace.fromString('#0 main (file.dart:1)'));
      await settle();
      expect(posted.single, {
        'message': 'Bad state: boom',
        'stack': '#0 main (file.dart:1)',
        'app_version': '1.2.3+45',
        'platform': 'android',
        'flavor': 'staff',
      });
    });

    test('nothing while signed out', () async {
      signedIn = false;
      reporter().report(StateError('boom'), null);
      await settle();
      expect(posted, isEmpty);
    });

    test('each message once, at most 5 per run, and a failing send is ignored', () async {
      final r = reporter();
      for (var i = 0; i < 3; i++) {
        r.report(StateError('same'), null);
        await settle();
      }
      for (var i = 0; i < 10; i++) {
        r.report(StateError('error $i'), null);
        await settle();
      }
      expect(posted.map((b) => b['message']), [
        'Bad state: same',
        'Bad state: error 0',
        'Bad state: error 1',
        'Bad state: error 2',
        'Bad state: error 3',
      ]);
      final failing = ErrorReporter(
        post: (_) async => throw const SocketException('offline'),
        signedIn: () => true,
        appVersion: 'v',
        platform: 'android',
        flavor: 'owner',
      );
      failing.report(StateError('x'), null);
      await settle();
      expect(failing.sentCount, 1);
    });

    test('a huge stack is cut to keep the report within 16 KB', () async {
      final stack = StackTrace.fromString(List.generate(5000, (i) => '#$i frame_$i (package:x/y.dart:$i:1)').join('\n'));
      reporter().report(Exception('x' * 50000), stack);
      await settle();
      final body = posted.single;
      expect(utf8.encode(jsonEncode(body)).length, lessThanOrEqualTo(ErrorReporter.maxBytes));
      expect(body['stack'], startsWith('#0 frame_0'));
      expect(body['message']!.length, lessThan(2100));
    });

    test('tokens and passwords never leave the phone', () {
      const jwt = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.c2lnbmF0dXJl';
      final text = ErrorReporter.scrub(
        'Authorization: Bearer abc.def-ghi token $jwt {"refresh_token":"r3fr3sh","password":"hunter22"} access_token=xyz',
      );
      expect(text, isNot(contains('abc.def-ghi')));
      expect(text, isNot(contains(jwt)));
      expect(text, isNot(contains('r3fr3sh')));
      expect(text, isNot(contains('hunter22')));
      expect(text, isNot(contains('xyz')));
      expect(text, contains('[removed]'));
    });
  });

  group('visit retention', () {
    test('a visit whose phone position was removed after 12 months still loads', () {
      final json = jsonDecode(handwritten('visit_location_removed')) as Map<String, dynamic>;
      final v = ShopVisit.fromJson(json['visit'] as Map<String, dynamic>);
      expect(v.deviceLat, isNull);
      expect(v.deviceLng, isNull);
      expect(v.locationRemoved, isTrue);
      expect(v.distanceM, 12);
      expect(v.status, VisitState.verified);
    });
  });
}
